### ISSUE TITLE
Nyt ikon - 

### ISSUE THREAD

**Issue by DKbest** [SDFIdk/design-system-css#12]
Der er oprettet et nyt ikon der kan tilføjes https://sdfidk.github.io/design-system-css/#icons

Question-Icon  (oprettet til brug i kortmenulinje på Dataforsyningen - 'Hjælp') 
![Question-Icon](https://user-images.githubusercontent.com/79503214/198281460-34cf348f-d19d-4c4f-91a4-219323eee218.svg)

Original findes i Figma: https://www.figma.com/file/G9g2vp2MOcejoPB3d1xJvU/Dataforsyningen-Design-System?node-id=106%3A3297

**Comment by DKbest** [comment]
Helt fint - det haster ikke :)

**Comment by iamfrank** [comment]
Nyt icon er tilføjet og publiseret:
https://sdfidk.github.io/design-system-icons/#icon-question

**Comment by DKbest** [comment]
Perfekt - tak 👍 
Og så må vi et tidspunkt have en snak om hvorfor ikonerne ser bedre og mere skarpe ud på https://sdfidk.github.io/design-system-icons/#map-icon-move sammenlignet med visningen af samme ikon på Dataforsyningen.
![image](https://user-images.githubusercontent.com/79503214/203256596-504f37a0-8554-4905-be40-12e09be28a10.png)
