### ISSUE TITLE
Not enough contrast for links in light data theme

### ISSUE THREAD

**Issue by heidivanparys** [SDFIdk/design-system-css#37]
The light color scheme results in web accessibility contrast errors for links:

![image](https://github.com/SDFIdk/design-system-css/assets/11427611/8f11e13e-822b-4149-8198-8aad4603e9a1)

![image](https://github.com/SDFIdk/design-system-css/assets/11427611/def185b8-f004-4f90-839d-8076f22f1bdf)

**Comment by iamfrank** [comment]
Fixed in version 3.9.1
