### ISSUE TITLE
Nye ikoner - Ruler og Move

### ISSUE THREAD

**Issue by DKbest** [SDFIdk/design-system-css#9]
Der er oprettet to nye ikoner der kan tilføjes https://sdfidk.github.io/design-system-css/#icons

Move
'Flyt kort' (kan det angives som mouseover?)
![Map-Icon_Move](https://user-images.githubusercontent.com/79503214/185344236-7fcae635-94d0-4550-92c1-286b82fec10b.svg)

Ruler 
'Mål i kort' (mouseover)
![Map-Icon_Ruler](https://user-images.githubusercontent.com/79503214/185344238-bf1ca0dd-2ad2-46b5-9815-ad17b72026ca.svg)

Original findes i Figma: https://www.figma.com/file/G9g2vp2MOcejoPB3d1xJvU/Dataforsyningen-Design-System?node-id=106%3A3297

**Comment by iamfrank** [comment]
Jeg ser på at inkludere dem nu.

**Comment by iamfrank** [comment]
Nye ikoner er integreret i design-system-icons - https://sdfidk.github.io/design-system-icons/
